import cookieParser from "cookie-parser";
import cors from "cors";
import express, { Request, Response } from "express";
import swaggerUi from "swagger-ui-express";
import { globalErrorHandler } from "./middlewares/globalErrorHandler";
import notFound from "./middlewares/notFound";
import adminRouter from "./module/admin/admin.router";
import authRouter from "./module/auth/auth.router";
import blogRouter from "./module/blog/blog.router";
import userRouter from "./module/user/user.router";
import swaggerSpec from "./swagger";
import dotenv from 'dotenv';


const app = express();
dotenv.config();

//// CORS configuration open for development, do not use in production due to security reasons
app.use(
  cors({
    origin: "*",
    credentials: true,
  })
);

// Parsers
app.use(express.json());
app.use(cookieParser());

// Routes
app.use("/api/v1/auth", authRouter);
app.use("/api/v1/admin", adminRouter);
app.use("/api/v1/user", userRouter);
app.use("/api/v1/blogs", blogRouter);


//For API documentation which is generated by swagger 
if (process.env.NODE_ENV === "development") {
  app.use(
    "/api/api-docs",
    swaggerUi.serveFiles(swaggerSpec),
    swaggerUi.setup(swaggerSpec)
  );
} else {
  app.use("/api/api-docs", swaggerUi.serve, swaggerUi.setup(swaggerSpec));
}

app.get("/api/swagger.json", (req, res) => {
  res.setHeader("Content-Type", "application/json");
  res.send(swaggerSpec);
});


// Health check route
app.get("/", (req: Request, res: Response) => {
  res.send({
    status: true,
    message: "Server is now Live - Alhamdulillah",
  });
});

// Error handling
app.use(globalErrorHandler);
app.use(notFound);

export default app;
